%YAML 1.1
---
log_configs:
  log_filename: "/tmp/aroundvision/AROUNDVISION-"
  log_level: "DEBUG"
  log_format: "[%(asctime)s - %(filename)s:%(lineno)s -  %(funcName)s() - %(levelname)s ] %(message)s"
  log_extension: ".log"
ui_configs:
  stylesheet: "aroundvision.css"
  ui_mainwindow: "mainwindow.ui"
  ui_loadsource: "load_source.ui"
  ui_popup: "popup.ui"
  roi_window: "region_of_interest.ui"
  roi_settings: "roi_settings.ui"
api_configs:
  api_endpoint: "http://0.0.0.0:5000/"
  api_stream_list_path: "get_stream_list"
  api_select_stream_path: "select_stream"
  api_get_frame_raw_path: "get_frame_raw"
  api_selected_stream_idx: "0"
frame_delay: 0.001
projections:
  - "Equirectangular"
  - "Cube Map"
  - "Equi-Angular Cubemap"
  - "Pyramid format"
qualities:
  - "1"
  - "2"
  - "3"
  - "4"
faces_cube:
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
roi_bitrate_value: "22"
roi_bitrate_units: "Mbits/s"
roi_quality: "4"
roi_qualities:
  - "1"
  - "2"
  - "3"
  - "4"
icons:
  play_icon: "play-circle-solid_ok.png"
  pause_icon: "pause-circle-solid_ok.png"
  settings_icon: "settings-solid_ok.png"
...